version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: infovis
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  web:
    build: .
    volumes:
      - .:/app
    entrypoint: /app/docker-entrypoint.sh
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db-data: